create routing and pagination
yurii-kdz/magnificent-spa pull request #5
Opened 2020-10-22 14:45 UTC by yurii-kdz

create routing and pagination

2020-10-23 08:53 UTC, ArtGarm requested changes

2020-10-23 08:53 UTC, ArtGarm commented on my-app/src/App.js
> +            <Router>
why no switch inside the router?

2020-10-23 08:53 UTC, ArtGarm commented on my-app/src/components/Body/Content/BlogView/BlogView.jsx
> +    const location = useLocation();
why not enough useParams?

2020-10-23 08:53 UTC, ArtGarm commented on my-app/src/components/Body/Content/Content.jsx
> +                () => <BlogView/>
why the component is arrow function?

2020-10-23 08:53 UTC, ArtGarm commented on my-app/src/components/Body/Content/Content.jsx
> +            </Route>
use route component in same style

2020-10-23 08:53 UTC, ArtGarm commented on my-app/src/components/Body/Content/CreateView/style.js
> +        fontSize: "16px",
use from typography

2020-10-23 08:53 UTC, ArtGarm commented on my-app/src/components/Body/Menu/mockup.js
> +        {text: "View site", icon: <Home viewBox="0 0 24 24"/>, route: "/"},
looks bad

2020-10-23 08:57 UTC, yurii-kdz commented on my-app/src/components/Body/Content/Content.jsx
> +                () => <BlogView/>
> why the component is arrow function?

if I don't use arrow function, my component doesn`t rerend after pressing on paginate button ¯\_(ツ)_/¯

2020-10-29 12:43 UTC, ArtGarm requested changes

2020-10-29 12:43 UTC, ArtGarm commented on my-app/src/components/Body/Content/Content.jsx
> +            <Route exact path="/createView" render={() => <CreateView/>}>
use this format
`<Route exact path="/createView" component={CreateView} />`

this format 
`<Route exact path="/createView" render={() => <CreateView/>}>`
used only if you need to drill some props

2020-11-11 14:41 UTC, ArtReactDev approved these changes

2020-11-11 14:41 UTC, merged